# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='dojo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dojos', to='dojoninja.Dojo'),
        ),
    ]
